presets:
  tv_pog:
    import_series:
      from:
        pogcal:
          username: ******
          password: ******
    exists_series:
      /media/icybox/raspi/Series
    deluge:
      path: /media/icybox/raspi/incomplete
      movedone: "/media/icybox/raspi/Series/{{ series_name }}/Season {{ series_season }}/"
  tv_dir:
    import_series:
      from:
        listdir: /media/icybox/raspi/Series
    exists_series:
      /media/icybox/raspi/Series
    deluge:
      path: /media/icybox/raspi/incomplete
      movedone: "/media/icybox/raspi/Series/{{ series_name }}/Season {{ series_season }}/"
  movies:
    imdb_lookup: yes
    deluge:
      path: /media/icybox/raspi/incomplete
      movedone: "/media/icybox/raspi/Movies/{{ movie_name }}"

      

tasks:
  seriesDL:
    preset: tv_dir
    rss: **********
  moviesDL:
    preset: movies
