presets:
  tv_pog:
    import_series:
      from:
        pogcal:
          username: ******
          password: ******
    exists_series:
      /media/storage/Series
    deluge:
      path: /media/storage/incomplete
      movedone: "/media/storage/Series/{{ series_name }}/Season {{ series_season }}/"
  tv_dir:
    import_series:
      from:
        listdir: /media/storage/Series
    exists_series:
      /media/storage/Series
    deluge:
      path: /media/storage/incomplete
      movedone: "/media/storage/Series/{{ series_name }}/Season {{ series_season }}/"
  movies:
    imdb_lookup: yes
    deluge:
      path: /media/storage/incomplete
      movedone: "/media/storage/Movies/{{ movie_name }}"

      

tasks:
  seriesDL:
    preset: tv_dir
    rss: **********
  moviesDL:
    preset: movies
    rss: http://127.0.0.1/feed.php
    accept_all: yes
