presets:
  tv:
    import_series:
      from:
        pogcal:
          username: ******
          password: ******
    exists_series:
      /media/storage/Series
    deluge:
      user: localclient
      pass: ******
      path: /media/storage/incomplete
      movedone: "/media/storage/Series/{{ series_name }}/Season {{ series_season }}/"

  tv_hack:
    import_series:
      from:
        listdir: /media/storage/Series
    exists_series:
      /media/storage/Series
    deluge:
      user: localclient
      pass: ******
      path: /media/storage/incomplete
      movedone: "/media/storage/Series/{{ series_name }}/Season {{ series_season }}/"

  movies:
    imdb_lookup: yes
    deluge:
      user: localclient
      pass: ******
      path: /media/storage/incomplete
      movedone: "/media/storage/Movies/{{ movie_name }}"



tasks:
  seriesDL:
    preset: tv
    rss: http://showrss.info/rss.php?user_id=******
  moviesDL:
    preset: movies
    rss: http://127.0.0.1/feed.php
    accept_all: yes

